services:
  backrest:
    container_name: backrest
    hostname: backrest
    image: ghcr.io/garethgeorge/backrest:latest
    ports:
      - "192.168.51.25:9898:9898"
    environment:
      BACKREST_PORT: 0.0.0.0:9898
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
      TMPDIR: /tmp
      TZ: America/New_York
    volumes:
      - restic-data:/repo
      - backrest-data:/data
      - backrest-config:/config
      - backrest-cache:/cache
      - backrest-tmp:/tmp
    restart: unless-stopped

volumes:
  restic-data:
    name: restic-data
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.8,nfsvers=4,rw,hard
      device: ":/mnt/MediaStorage/Backups"

  backrest-data:
    name: backrest-data
  backrest-config:
    name: backrest-config
  backrest-cache:
    name: backrest-cache
  backrest-tmp:
    name: backrest-tmp
