services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      TZ: America/New_York
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  homarr:
    container_name: homarr
    hostname: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    ports:
      - "7575:7575"
    environment:
      TZ: America/New_York
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    volumes:
      - ./homarr:/appdata
    restart: unless-stopped
volumes:
  npm_data:
    name: npm_data
  npm_letsencrypt:
    name: npm_letsencrypt
